### ISSUE TITLE
Granting Collaborator permissions to @codifryed

### ISSUE THREAD

**Issue by leinardi** [flathub/com.leinardi.gkraken#14]
I would like to extend the Collaborator permissions for this repository to @codifryed. I would like to give him the same level of permissions that I have, so that he could be able to make new releases of the app.

I did not find a way to change the permission myself so I'll try to quote here some of the people from the Flathub project (sorry for the spam).

@alexlarsson @barthalion @bilelmoussaoui @dbnicholson

**Comment by bilelmoussaoui** [comment]
You should open an issue in flathub/flathub next time, we can't track all the various repositories. Invitation sent.

**Comment by leinardi** [comment]
Thanks, I will!

**Comment by codifryed** [comment]
accepted and verified working, thanks!
