### ISSUE TITLE
Maybe more of question.

### ISSUE THREAD

**Issue by M-Brody** [flathub/com.leinardi.gkraken#3]
First off. Thank you so much for making this app! You rock!

My "issue" (more like a question) is about the new Kraken AIO models. NZXT recently released their next generation of AIO coolers. I specifically have the Kraken X53.

When I launch your app I get a message about checking the usb connection and I wanted to check before taking my build apart to get to that header that it wasn't a compatibility issue. I noticed you only list the previous generation of coolers.

Are you planning on adding compatibility for the new coolers? Or do you think my issue is just related to my build?

![Screenshot](https://user-images.githubusercontent.com/45641133/74705604-59ecd580-520c-11ea-8c54-4555dca798fa.png)

**Comment by leinardi** [comment]
Hi @M-Brody, currently GKraken supports only X42, X52, X62 and X72.

**Comment by jonasmalacofilho** [comment]
Hi @M-Brody.

The communication with the coolers is handled by liquidctl, so you probably want to help out on jonasmalacofilho/liquidctl#78.

**Comment by leinardi** [comment]
The X53 is supported starting from version 1.0.0: https://gitlab.com/leinardi/gkraken/-/releases/1.0.0
